export const UI_ELEMENTS = {
  'WEATHER_FORM': document.querySelector('.weather-app__form'),
  'WEATHER_INPUT': document.querySelector('.weather-app__input'),
  'WEATHER_ITEMS': Array.from(document.querySelectorAll('.weather__item')),
  'WEATHER_NOW': document.querySelector('.weather-now'),
  'WEATHER_NOW_MESSAGE': document.querySelector('.weather-now__message'),
  'WEATHER_NOW_CONTENT': document.querySelector('.weather-now__content'),
  'WEATHER_NOW_CITY': document.querySelector('.weather-now__city'),
  'WEATHER_NOW_TEMPERATURE': document.querySelector('.weather-now__temperature'),
  'WEATHER_NOW_FAVOURITE_CITY_BUTTON': document.querySelector('.weather-now__favourite-btn'),
  'WEATHER_FAVOURITE_CITIES_MESSAGE': document.querySelector('.weather-favourite-cities__message'),
  'WEATHER_FAVOURITE_CITIES_CONTENT': document.querySelector('.weather-favourite-cities__content'),
  'WEATHER_FAVOURITE_CITIES_LIST': document.querySelector('.weather-favourite-cities__list'),
  'WEATHER_DETAILS': document.querySelector('.weather-details'),
  'WEATHER_DETAILS_TITLE': document.querySelector('.weather-details__title'),
  'WEATHER_DETAILS_LIST': document.querySelector('.weather-details__list'),
  'WEATHER_FORECAST': document.querySelector('.weather-forecast'),
  'WEATHER_TABS': document.querySelector('.weather-app__weather-tabs'),
  'WEATHER_TAB_ITEMS': Array.from(document.querySelectorAll('.weather-app__weather-tab')),
};
